ALTER TABLE mp3server ADD COLUMN IF NOT EXISTS volume_alarm INTEGER DEFAULT 100 NOT NULL;
ALTER TABLE mp3server ADD COLUMN IF NOT EXISTS volume_waiting INTEGER DEFAULT 100 NOT NULL;
ALTER TABLE mp3server ADD COLUMN IF NOT EXISTS volume_warning INTEGER DEFAULT 100 NOT NULL;
